version: '3.9'

services:
  postgres-db:
    image: postgres:17
    container_name: my-postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/testdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"  
    depends_on:
      - postgres-db

  angular-frontend:
    build:
      context: ./angular-17-client   
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:4200"  
    depends_on:
      - springboot-app

volumes:
  postgres-data:
